syntax on      
 
filetype on
filetype plugin
filetype indent

## Disable mouse
set mouse-=a
set ttymouse=

## File format and UniCode for default
set encoding=utf-8
set fileformat=unix

## Rules numbers gide
set ruler
set number
set cursorline
set cursorcolumn
set relativenumber

set autoindent
set numberwidth=2
set shiftwidth=2
set tabstop=2
set expandtab
set showcmd
set showmode
set showmatch

let g:netrw_keepdir = 0
let g:netrw_winsize = 20
let g:netrw_banner = 0
hi! link netrwMarkFile Search

## Autocomplete
inoremap " ""<left>
inoremap ' ''<left>
inoremap < <><left>
inoremap ( ()<left>
inoremap [ []<left>
inoremap { {}<left>
inoremap {<CR> {<CR>}<ESC>O
inoremap {;<CR> {<CR>};<ESC>O
